name: Push public container in org that has just private visibility
on: push
jobs:
 all:
  runs-on: ubuntu-latest
  steps: 
  - run: brew install skopeo
  - run: sudo skopeo copy --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}  docker://docker.io/library/python:latest docker://ghcr.io/orgdwivedine/python:latest

  # run: sudo skopeo login -u '${{ github.actor }}' -p '${{ secrets.GITHUB_TOKEN }}' ghcr.io
  # run: sudo skopeo copy --override-os linux docker://docker.io/library/alpine:latest docker://ghcr.io/orgdwivedine/alpine:latest
